# Generated by Django 5.2 on 2025-04-11 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mfa', '0002_customuser_mfa_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='mfa_secret',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
